<a href="https://colab.research.google.com/github/brahmanbhavika06-sketch/my-colab-code/blob/main/Optional_task_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!unzip archive.zip

Archive:  archive.zip
  inflating: cardekho.csv
 extracting: archive (1).zip

In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import joblib

In [11]:
import pandas as pd

# Load Dataset
df = pd.read_csv("cardekho.csv")

# Display first 10 rows
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14,1197.0,81.86,5.0
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.30,1061.0,57.5,5.0
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.10,796.0,37,4.0
8,Toyota Etios VXD,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59,1364.0,67.1,5.0
9,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.00,1399.0,68.1,5.0

In [10]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage(km/ltr/kg)', 'engine', 'max_power',
       'seats'],
      dtype='object')

In [12]:
# Independent Features
X = df.drop("selling_price", axis=1)

# Dependent Feature
y = df["selling_price"]

print("Shape of X :", X.shape)
print("Shape of y :", y.shape)

Shape of X : (8128, 11)
Shape of y : (8128,)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ['year', 'km_driven']

for col in num_cols:
    if col in X.columns:
        X[col] = scaler.fit_transform(X[[col]])

X.head()

,year,km_driven,mileage(km/ltr/kg),engine,seats,name_Ambassador CLASSIC 1500 DSL AC,name_Ambassador Classic 2000 DSZ AC PS,name_Ambassador Grand 1500 DSZ BSIII,name_Ambassador Grand 2000 DSZ PW CL,name_Ashok Leyland Stile LE,...,max_power_98.59,max_power_98.6,max_power_98.63,max_power_98.79,max_power_98.82,max_power_98.96,max_power_98.97,max_power_99,max_power_99.23,max_power_99.6
0,0.048464,1.338363,23,1248,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.048464,0.887411,21,1498,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-1.929775,1.241098,17,1497,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-0.940656,1.011202,23,1396,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-1.682495,0.887411,16,1298,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

print("X_train :", X_train.shape)
print("X_test :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test :", y_test.shape)

X_train : (5445, 2397)
X_test : (2683, 2397)
y_train : (5445,)
y_test : (2683,)

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Intercept :", model.intercept_)

print("Coefficients :")
print(model.coef_)

Intercept : 961006.0609119477
Coefficients :
[ 123775.71312605  -10005.73332804    5564.86437686 ... -232234.28032476
 -151423.429062   -117577.39673758]

In [22]:
y_pred = model.predict(X_test)

print("First 10 Predicted Values:")
print(y_pred[:10])

print()

print("First 10 Actual Values:")
print(y_test.head(10).values)

First 10 Predicted Values:
[198000.00000146 398622.17370801 424268.68944402 214881.05673248
 388098.23320445 155601.89245266 660730.02316049 477919.1346618
 219991.98750163  66598.97102509]

First 10 Actual Values:
[198000 500000 425000 150000 525000 160000 450000 570000 170000 135000]

In [23]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_pred)

print("R² Score :", score)

R² Score : 0.9002560573899328