<a href="https://colab.research.google.com/github/brahmanbhavika06-sketch/my-colab-code/blob/main/Session20_Ford_Car_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!unzip "archive (1).zip"

Archive:  archive (1).zip
  inflating: ford.csv

In [7]:
import pandas as pd

# Load Dataset
df = pd.read_csv("ford.csv")
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [5]:
# Independent Features (X)
X = df.drop("price", axis=1)

# Dependent Feature (Y)
Y = df["price"]

# Shape
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (17966, 8)
Shape of Y: (17966,)

In [8]:
X.select_dtypes(include='object').columns

Index(['model', 'transmission', 'fuelType'], dtype='object')

In [13]:
# Step 1: Find Categorical Columns
X.select_dtypes(include='object').columns

# Step 2: One-Hot Encoding
X = pd.get_dummies(X)

# Step 3: Convert into Integer
X = X.astype(int)

# Step 4: Display first 5 rows
X.head()

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_cols = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
X[num_cols] = scaler.fit_transform(X[num_cols])
X.head()

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.065128,-0.380998,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0.552866,-0.733359,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0.065128,-0.560132,0.591358,-0.042122,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,1.040605,-0.662640,0.510727,-1.721198,-0.447984,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,1.040605,-1.123724,0.510727,-0.931045,-0.447984,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.33,
    random_state=42
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

X_train Shape: (12037, 37)
X_test Shape: (5929, 37)
y_train Shape: (12037,)
y_test Shape: (5929,)

In [22]:
from sklearn.linear_model import LinearRegression

# Create Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

# Print Intercept
print("Intercept:", model.intercept_)

# Print Coefficients
print("Coefficients:")
print(model.coef_)

Intercept: 17008.92880446365
Coefficients:
[ 2.03726418e+03 -1.31955378e+03 -2.12184657e+01 -9.89026938e+02
  8.79613637e+02 -3.65234589e+03 -2.68053102e+03 -2.36339814e+03
  4.80150971e+03  1.02450948e+04 -2.72586392e+03 -6.34300645e+02
 -1.61638167e+02  2.03975409e+03 -2.41408106e+03  3.63649958e+02
 -4.09377412e+03 -6.56211930e+03 -4.23908486e+02 -1.23180996e+03
  9.37077816e+03  3.56715981e+03  1.59161573e-12  1.88351384e+03
 -1.81898940e-12 -2.25529492e+02  1.90037677e+03 -2.78174995e+03
 -4.22078695e+03  2.52157947e+02 -2.56550681e+02  4.39273388e+00
 -2.00100839e+03  0.00000000e+00  6.64511383e+03 -1.34334791e+03
 -3.30075753e+03]

In [23]:
# Make Predictions
y_pred = model.predict(X_test)

# Print Predicted Values
print("Predicted Values:")
print(y_pred[:10])

# Print Actual Values
print("Actual Values:")
print(y_test.iloc[:10])

Predicted Values:
[ 6888.75487917  9328.62297666  9420.53085767  4495.6044587
  2429.68493278 16982.00675592 28491.10791141 12482.71267443
 11373.08042083 17275.68925414]
Actual Values:
17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
14735    18200
322      22998
8164     11000
6822      7600
2133     14985
Name: price, dtype: int64

In [24]:
from sklearn.metrics import r2_score

# Calculate R² Score
r2 = r2_score(y_test, y_pred)

# Print Score
print("R² Score:", r2)

R² Score: 0.8401880779365886

In [25]:
import joblib

# Save Linear Regression Model
joblib.dump(model, "LR_ford_car.pkl")

# Save StandardScaler
joblib.dump(scaler, "scaler.pkl")

# Save Column Names
joblib.dump(X.columns.tolist(), "columns.pkl")

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!